stages :
  - build
  - deploy

build :
  image : maven:3.8-openjdk-16
  stage : build
  script : mvn clean package -DskipTests
  only :
    - develop

deploy :
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - echo "SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE" >> .env
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop