package com.synrgybootcamp.project.enums;

public enum MissionType {
    TRANSFER,
    POCKET,
    PAYMENT_MERCHANT,
    PAYMENT_MOBILE_CREDIT,
    PAYMENT_PDAM,
    PAYMENT_ELECTRICITY,
    PAYMENT_TELEVISION,
    PAYMENT_TRAIN,
    PAYMENT_DONATION,
    PAYMENT_INSURANCE
}
